services:
  postgres:
    image: postgres:15
    container_name: node-admin-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: node_admin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: node-admin-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5433/node_admin_db
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: node-admin-frontend
    environment:
      NODE_ENV: development
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run start

volumes:
  postgres_data:
